apiVersion: v1
kind: Pod

metadata:
  name: backend
  namespace: default
  labels:
    app: backend
    group: al2

spec:
  containers:
    - name: backend
      image: babyteacher-registry/backend:latest
      ports:
        - name: web
          containerPort: 3001
