name: 'Terraform deployment'

on: 
  workflow_dispatch:
  
jobs:
  terraform:

    runs-on: ubuntu-latest
   
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform init
        run: terraform init
        working-directory: ./infra
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY_ID }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      
      # - name: Creating certificate
      #   run: |
      #     mkdir -p certs
      #     echo "${{ env.CERT_CRT }}" > certs/server.crt
      #     echo "${{ env.CERT_KEY }}" > certs/server.key

      - name: Terraform Apply
        working-directory: ./infra
        run: |
          terraform apply -auto-approve -input=false
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY_ID }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          
