name: 'Terraform deployment'

on: 
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup env var
        run: source init-config.sh
        shell: bash

      - name: Terraform init
        run: terraform init

      # - name: Creating certificate
      #   run: |
      #     mkdir -p certs
      #     echo "${{ env.CERT_CRT }}" > certs/server.crt
      #     echo "${{ env.CERT_KEY }}" > certs/server.key

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -input=false

      
        
        
