name: 'Terraform deployment'

on: 
  workflow_dispatch:
    inputs:
      front:
        description: 'Front commit hash'
        required: false
        default: 'latest'
        type: string

      back:
        description: 'Back commit hash'
        required: false
        default: 'latest'
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}

      TF_VAR_MYSQL_USER: ${{ secrets.MYSQL_USER }}
      TF_VAR_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      TF_VAR_MYSQL_ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
      TF_VAR_MONGO_USER: ${{ secrets.MONGO_USER }}
      TF_VAR_MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      TF_VAR_FRONT_TAG: ${{ github.event.inputs.front }}
      TF_VAR_BACKEND_TAG: ${{ github.event.inputs.back }}
   
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
       
      - name: Terraform init
        run: terraform init
        working-directory: ./infra
        
      - name: Terraform Apply
        working-directory: ./infra
        run: |
          terraform apply -auto-approve -input=false
